/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FunnelContractJson } from "../Funnel.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Entries, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace FunnelTypes {
  export type Fields = {
    count: bigint;
    raffle: bigint;
    reward: bigint;
    lastrun: bigint;
    leadingentry: bigint;
    leadingamount: bigint;
  };

  export type State = ContractState<Fields>;

  export type NewEntryEvent = ContractEvent<{
    by: Address;
    to: Address;
    agent: Address;
    value: bigint;
  }>;
  export type NewRaffleEvent = ContractEvent<{
    by: Address;
    winner: Address;
    amount: bigint;
    timestamp: bigint;
  }>;
  export type NewRewardEvent = ContractEvent<{
    by: Address;
    winner: Address;
    amount: bigint;
    timestamp: bigint;
  }>;

  export interface CallMethodTable {
    createEntry: {
      params: CallContractParams<{ amt: bigint; to: Address; ag: Address }>;
      result: CallContractResult<null>;
    };
    raffleDist: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    rewardDist: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createEntry: {
      params: SignExecuteContractMethodParams<{
        amt: bigint;
        to: Address;
        ag: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    raffleDist: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    rewardDist: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { entries?: Map<bigint, Entries> };
}

class Factory extends ContractFactory<FunnelInstance, FunnelTypes.Fields> {
  encodeFields(fields: FunnelTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { NewEntry: 0, NewRaffle: 1, NewReward: 2 };
  consts = {
    ErrorCodes: {
      SelfPay: BigInt("0"),
      AgentPay: BigInt("1"),
      DataMalfunction: BigInt("2"),
      LackOfBal: BigInt("3"),
      NoneEligible: BigInt("4"),
      RaffleLow: BigInt("5"),
      RewardLow: BigInt("6"),
      OngoingCycle: BigInt("7"),
    },
  };

  at(address: string): FunnelInstance {
    return new FunnelInstance(address);
  }

  tests = {
    createEntry: async (
      params: TestContractParams<
        FunnelTypes.Fields,
        { amt: bigint; to: Address; ag: Address },
        FunnelTypes.Maps
      >
    ): Promise<TestContractResult<null, FunnelTypes.Maps>> => {
      return testMethod(this, "createEntry", params, getContractByCodeHash);
    },
    raffleDist: async (
      params: Omit<
        TestContractParams<FunnelTypes.Fields, never, FunnelTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<null, FunnelTypes.Maps>> => {
      return testMethod(this, "raffleDist", params, getContractByCodeHash);
    },
    rewardDist: async (
      params: Omit<
        TestContractParams<FunnelTypes.Fields, never, FunnelTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<null, FunnelTypes.Maps>> => {
      return testMethod(this, "rewardDist", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FunnelTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: FunnelTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Funnel = new Factory(
  Contract.fromJson(
    FunnelContractJson,
    "=5-2+12=2+20=1-2=2+c=1-1=13-1+4=10+7e011452756e6e696e672043726561746520456e747279=326+7a7e0214696e73657274206174206d617020706174683a2000=171-1+b=10+7e011b52756e6e696e6720526166666c6520446973747269627574696f6e=351-1+3=10+7e011b52756e6e696e672052657761726420446973747269627574696f6e=308",
    "b88da040afa4f755b70ef27eae7b5cdd02b0dd9b216ab6395eb30203749333b6",
    AllStructs
  )
);
registerContract(Funnel);

// Use this class to interact with the blockchain
export class FunnelInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    entries: new RalphMap<bigint, Entries>(
      Funnel.contract,
      this.contractId,
      "entries"
    ),
  };

  async fetchState(): Promise<FunnelTypes.State> {
    return fetchContractState(Funnel, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNewEntryEvent(
    options: EventSubscribeOptions<FunnelTypes.NewEntryEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Funnel.contract,
      this,
      options,
      "NewEntry",
      fromCount
    );
  }

  subscribeNewRaffleEvent(
    options: EventSubscribeOptions<FunnelTypes.NewRaffleEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Funnel.contract,
      this,
      options,
      "NewRaffle",
      fromCount
    );
  }

  subscribeNewRewardEvent(
    options: EventSubscribeOptions<FunnelTypes.NewRewardEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Funnel.contract,
      this,
      options,
      "NewReward",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | FunnelTypes.NewEntryEvent
      | FunnelTypes.NewRaffleEvent
      | FunnelTypes.NewRewardEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Funnel.contract, this, options, fromCount);
  }

  view = {
    createEntry: async (
      params: FunnelTypes.CallMethodParams<"createEntry">
    ): Promise<FunnelTypes.CallMethodResult<"createEntry">> => {
      return callMethod(
        Funnel,
        this,
        "createEntry",
        params,
        getContractByCodeHash
      );
    },
    raffleDist: async (
      params?: FunnelTypes.CallMethodParams<"raffleDist">
    ): Promise<FunnelTypes.CallMethodResult<"raffleDist">> => {
      return callMethod(
        Funnel,
        this,
        "raffleDist",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    rewardDist: async (
      params?: FunnelTypes.CallMethodParams<"rewardDist">
    ): Promise<FunnelTypes.CallMethodResult<"rewardDist">> => {
      return callMethod(
        Funnel,
        this,
        "rewardDist",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createEntry: async (
      params: FunnelTypes.SignExecuteMethodParams<"createEntry">
    ): Promise<FunnelTypes.SignExecuteMethodResult<"createEntry">> => {
      return signExecuteMethod(Funnel, this, "createEntry", params);
    },
    raffleDist: async (
      params: FunnelTypes.SignExecuteMethodParams<"raffleDist">
    ): Promise<FunnelTypes.SignExecuteMethodResult<"raffleDist">> => {
      return signExecuteMethod(Funnel, this, "raffleDist", params);
    },
    rewardDist: async (
      params: FunnelTypes.SignExecuteMethodParams<"rewardDist">
    ): Promise<FunnelTypes.SignExecuteMethodResult<"rewardDist">> => {
      return signExecuteMethod(Funnel, this, "rewardDist", params);
    },
  };
}
